### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by machist** [eidellev/inertiajs-adonisjs#74]
Hi, thanks for the wonderful solution.
React with typescript is working perfectly fine without SSR.

But when I try to make SSR enabled. I'm getting 

````bash
[1656072804998] ERROR (rita/2945 on machist): Unexpected token '<'
    err: {
      "type": "SyntaxError",
      "message": "Unexpected token '<'",
      "stack":
          /home/borag/Tmp/rita/resources/js/pages/auth/register.tsx:22
              return (<Layout_1.default links={[]}>
                      ^

          SyntaxError: Unexpected token '<'
              at Object.compileFunction (node:vm:352:18)
              at wrapSafe (node:internal/modules/cjs/loader:1033:15)
              at Module._compile (node:internal/modules/cjs/loader:1069:27)
              at Module._compile (/home/borag/Tmp/rita/node_modules/pirates/lib/index.js:136:24)
              at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
              at Object.newLoader [as .tsx] (/home/borag/Tmp/rita/node_modules/pirates/lib/index.js:141:7)
              at Module.load (node:internal/modules/cjs/loader:981:32)
              at Function.Module._load (node:internal/modules/cjs/loader:822:12)
              at Module.require (node:internal/modules/cjs/loader:1005:19)
              at require (node:internal/modules/cjs/helpers:102:18)
      "status": 500
    }
````

**Comment by machist** [comment]
I'm terribly sorry that I mixed _tsconfig.json_ files
In the [blog](https://dev.to/eidellev/getting-started-with-adonisjs-and-inertia-js-2po0) 
- added "jsx":"react" to "js/tsconfig.json"
- but it seems I also need to add the same to "tsconfig.json" at root.

That fixed by problem
